module.exports = [
  'My name is Barry Allen , ',
  'and I am the fastest man alive . ',
  'To the outside world , ',
  'Im an ordinary forensic scientist , ',
  'but secretly , with the help of my friends at S . T . A . R Labs , ',
  'I fight crime and find other metahumans like me . ',
  'I hunted down the man who killed my mother , ',
  'but in doing so , ',
  'I opened up our world to new threats . ',
  'And I am the only one fast enough to stop them . ',
  'I am The Flash . ',
  'Previously on "The Flash" And "Arrow" . ',
  'The person who broke into my facility last night',
  'was Harrison Wells . ',
  'Dr . Caitlin Snow , Cisco Ramon , ',
  'meet Dr . Harrison Wells from Earth2 . ',
  'I came here to help you , Barry . ',
  'He may not be Harrison Wells from your earth . ',
  'He has just as many secrets as the one you knew . ',
  'I get these feelings sometimes , these vibes . ',
  'Im not sure what triggers it . Sometimes it just happens . ',
  'You can always talk to me . ',
  'Partners ?  Partners . ',
  'This is a million dollars . ',
  'That money is yours once you tell Oliver that youve lost the baby . ',
  'Ive been running a lot lately , ',
  'trying to go faster than Ive ever gone before . ',
  'Because theres someone out there',
  'whos better , faster , and stronger than I am , ',
  'and I need to be ready . ',
  'But no matter how much I try or how hard I push myself , ',
  'I keep running into the same problem . ',
  'He just hit 1,375 . ',
  'Whats the fastest Barrys run ? ',
  'Little over Mach two , when he ran back in time . ',
  'Thats not good . ',
  'Thats good , Barry . ',
  'We have our work cut out for us . ',
  'Im not getting faster , am I ? ',
  'No , youre not . ',
  'All right , well , lets fix this , right ? ',
  'I mean , I cant beat Zoom at this speed . ',
  'It felt like I was standing still next to him . ',
  'Thats because you practically were . ',
  'Zoom is at least three , four times faster than you at this point . ',
  'How is he so much faster than Barry is and Jay was ? ',
  'Physiology , form , strength , could be a number of things',
  'attitude , diet . ',
  'Okay , all right , well , theres got to be something we can do about it , ',
  'so lets just figure it out . ',
  'Fast , okay ? ',
  'All right , I got to go . Im meeting Patty . ',
  'Ill see you . Thank you . ',
  'So how are we going to help Barry ? ',
  'Im out of ideas , ',
  'and weve tried everything youve suggested . ',
  'Well , not everything . ',
  'Welcome home . ',
  'Any trouble ?  Nah . ',
  'But believe it or not , we got ourselves a stowaway . ',
  'He give you his name ?  Didnt say . ',
  'Sat in the brig silent for three weeks . ',
  'He was all decked out in this when we found him . ',
  'Jeez , how many are there ?  32 . ',
  'And Ill polish them all in blood before long . ',
  'Ive waited a long time for this hunt , ',
  'and you have brought me very close to my prey . ',
  'Mister , youre not going to do any hunting in those handcuffs . ',
  'Oh , but , Captain , youre wearing the cuffs . ',
  'Who taught you that Houdini ? ',
  'Actually , I taught him . ',
  'Soon another sacrifice will be made . ',
  'I feel you out there . ',
  'Man , this was a bloodbath . ',
  'Done by one person . ',
  'One person did all this ? ',
  'Oh , yeah , you can see from the blood pattern . ',
  'This guy was shot first , then the police chief , ',
  'then these three were stabbed before finishing off the captain . ',
  'Do you think a metahuman did it ? ',
  'I dont know , but I found this',
  'in all of the stab victims wounds . ',
  'Its some type of cryptocrystalline flint , most likely',
  'probably broke off the blade during the fight . ',
  'Ill run it to make sure . ',
  'Lets see what stores sell those kind of flint knives . ',
  'Will do . ',
  'And , uh , Ill call you later . ',
  'Okay .  Okay . ',
  'So cute . ',
  'You guys are trying not to be affectionate in front of me . ',
  'Oh , no , were just showing some professionalism . ',
  'Yeah . ',
  'Advantages of a trusting manager . ',
  'Oh , a lots gone down in this place . ',
  'Nice . ',
  'So whats up ? ',
  'I thought we were gonna go to dinner . ',
  'Whoa . ',
  'Whats going on here ? ',
  'I couldnt decide which restaurant to go to , ',
  'so I thought we would create our own . ',
  'Voila . ',
  'Short rib , Yukon gold puree , and asparagus . ',
  'Got to have a vegetable . ',
  'This is nice . ',
  'I like to cook . ',
  'I didnt know if you like red or white , so . ',
  'I got you both . ',
  'Ooh , two bottles . ',
  'Thats kind dangerous , dont you think ? ',
  'Youre not gonna run away all of a sudden , are you ? ',
  'Trust me , Im staying by your side as long as possible . ',
  'Good . ',
  'You know , its been really great',
  'hanging out these last few weeks . ',
  'And its helped make the move a lot easier , so . ',
  'thanks . ',
  'Youre very welcome . ',
  'Sorry . How did you get in here ? ',
  'Hey , man , this place is closed . ',
  'You are just as beautiful in this life as any other , ',
  'Priestess ChayAra . ',
  'Priestess ? ',
  'Youre going to have to go , dude . ',
  'Oh , not without her . ',
  'dude . ',
  'Oh , my God . Cisco . ',
  'I dont understand . What do you want ? ',
  'I believe I was clear . ',
  'Kendras not going anywhere with you , Highlander . ',
  'Oh , is that your name now ? ',
  'Kendra quite boring . ',
  'I believe it allowed you to blend in for a while . ',
  'Now , give her to me , and Ill make your death fast . ',
  'It aint gonna happen . ',
  'You are done here , pal . ',
  'So is he ! ',
  'Thank God , Barry . ',
  'Dude , come on . ',
  'I cant believe youre The Flash . ',
  'And that you work with The Flash . ',
  'Yeah , lets keep that on the DL . ',
  'This is the same knife that was used to kill the men at the docks . ',
  'Residue is a perfect match . ',
  'So it is the same guy .  Definitely . ',
  'But the thing is , these blades are old , ',
  'centuries old . ',
  'Do you have any idea why this guy would be after you ? ',
  'No , Ive never seen him before in my life . ',
  'Well , he was certainly acting like he knew you . ',
  'He kept calling her Priestess ChayAra . ',
  'Thats Coptic . ',
  'You mean Egyptian ?  Thats right . ',
  'Well , I grew up in Wisconsin , ',
  'and Ive never even left the States , so . ',
  'This guy , hes clearly incredibly dangerous , ',
  'so I need you to at least let us try to protect you . ',
  'I can put a detail on her . ',
  'You didnt see this guy , Joe . ',
  'No offense , but I dont think a cop is going to be able to protect her . ',
  'No , but we do have a few friends who could lend a hand . ',
  'But were going to need to leave Central City . ',
  'And go where ? ',
  'You really want to go to Star City ? ',
  'Come on , we dont need Team Arrows help . ',
  'Yeah , I think we do , man . ',
  'Man , youve fought metahumans',
  'with abilities a lot worse than knifethrowing . ',
  'I dont think this guys a metahuman . ',
  'Theres something different about him , ',
  'something , ah , mystical . ',
  'Mystical , really ? ',
  'We stop metahumans because were scientists . ',
  'We can figure out what their weaknesses are , ',
  'but we dont have any experience when it comes to guys like this , ',
  'with magic . They do . ',
  'This wouldnt have anything to do with Zoom , would it ? ',
  'No . ',
  'Im just trying to keep Kendra safe . ',
  'This is the best way to do that . ',
  'Right . Okay , Im with you . ',
  'But how do we even know Oliver and them',
  'even have time to help us ? ',
  'How busy can they be ? ',
  'Oh , gosh , thats fun . ',
  'I really could do this all day . ',
  'Open it up . ',
  'They couldve at least tried to hide this chemical bomb . ',
  'Serves them right , it getting stolen and used against them . ',
  'Oh , you brought arrows to a gunfight . ',
  'What guns ? ',
  'Oh , that was actually pretty clever . ',
  'Kill them . ',
  'Felicity , the magneticarrow gag will never work."',
  'Yes , it will , my love , ',
  'because I am really smart . ',
  'And guess what , Oliver . It did work . ',
  'Felicity , honey , its a little hard to fight',
  'with you doing that in my ear . ',
  'Oh , I totally forgot that this was an open line . ',
  'Keep doing what youre doing . Make smart decisions . ',
  'Ooh ! You know , I got to be honest . ',
  'I really thought wed be doing this dance a lot longer . ',
  'Nightnight . ',
  'What was that ? ',
  'Damn it . ',
  'Every time . ',
  'Its The Flash . ',
  'Did I know we knew The Flash ? ',
  'We know The Flash . Okay . ',
  'I didnt know we knew The Flash .  Thank you . ',
  'But I dont think you ran all the way here to protect us . ',
  'No , not to protect you . ',
  'I need to protect a friend . ',
  'Nice new digs . ',
  'Also , I just noticed , no sleeves . ',
  'Dont you get cold ? ',
  'I spent the better part of five years on an island',
  'in the North China Sea . ',
  'I dont get cold , Barry . ',
  'Barry , its so good to see you . ',
  'Felicity . ',
  'Good to see you , Felicity . ',
  'How come you didnt tell me Zoom broke your back ? ',
  'I.  Oh , Im so glad youre okay . ',
  'So this is what its like dating her ? ',
  'More bruises from her than from Deathstroke . ',
  'Okay , S . T . A . R . Labs is impressive , but this is . ',
  'This is completely wrong ! ',
  'Did you guys even look at the specs I sent over ? ',
  'This is a tragedy . ',
  'Im mourning for the death of engineering . ',
  'Copper wiring to handle the processing speed',
  'from the Palmer Satellite , ',
  'or else your system is gonna overload . ',
  'Yeah , but that hasnt happened . ',
  'I mean , it hasnt happened since last week . ',
  'I mean , it didntIt happened yesterday . ',
  'Im Felicity . ',
  'Im Kendra Saunders . Im Ciscos . ',
  'Shes , uh , my , uh , new , beautiful friend',
  'who kisses me occasionally . ',
  'Right . Um , Im Thea . ',
  'This is John Diggle and my brother . ',
  'Oliver Queen . ',
  'Wow . Okay , first to meet The Flash',
  'and now the Green Arrow . ',
  'Do you have any other surprises for me ? ',
  'Please , no more surprises . ',
  'Barry said that you need our help . ',
  'Somebody very dangerous is after you . ',
  'Yeah , and I have no idea why . ',
  'What does this guy even look like ? ',
  'Hold on . ',
  'Okay , this is him . ',
  'Yeah , see , thats something I would never think of . ',
  'Hey , kind of rocking that Dothraki lookhot . ',
  'Lets see if facial recognition can find a match . ',
  'Thats him .  Yeah , strange . ',
  'This pictures from 1975 . ',
  'Which would make him about 80 years old right now . ',
  'Okay , what else can you tell us ? ',
  'He said weve known each other for ages , ',
  'but Ive never met the man before . ',
  'There has to be some kind of connection . ',
  'Not one I can think of . ',
  'I just moved to Central City six months ago . ',
  'Whyd you move there ? ',
  'I just felt drawn to the city , I guess . ',
  'Kendra , there is a reason this guys after you . ',
  'Think . ',
  'Look , man , we just came out here to hide out for a bit',
  'until we figure things out , so you can just take it down . ',
  'You came here because you need our help . ',
  'This is what my help looks like . ',
  'Oliver , I just saved you guys',
  'from whatever the hell Flock of Seagulls was about to do . ',
  'The least you can do is',
  'Barry , none of us have superpowers . ',
  'You brought Kendra into our world',
  'without knowing who she is',
  'or what this dude that is after her is looking for . ',
  'You made all of us unsafe . ',
  'So maybe you ask the questions . ',
  'Were all friends here , right ? ',
  'Why dont we go back to our place',
  'and have some drinks , and we can talk ? ',
  'Cool . ',
  'What you working on ? ',
  'This is a formula',
  'meant to increase a speedsters velocity',
  'that Ive been developing since Zoom showed up on my earth . ',
  'Ironically , this was meant to help out Jay Garrick . ',
  'You want to give Barry a drug to make him run faster ? ',
  'Temporarily enhance the Speed Force in his system , yes . ',
  'So youre trying to make nitrous oxide for speedsters . ',
  'Good analogy . Yes , I tried . ',
  'Five times I tried . Five times I failed . ',
  'Thats what you get when your background is technology',
  'and not biochemistry . ',
  'Well , then you are lucky I am here . ',
  'What does that mean ? ',
  'Youve been thinking of this',
  'as a mechanical problem , not a biomechanical one . ',
  'And what does that mean ? ',
  'When a speedster runs , they consume an extraordinary amount of oxygen , ',
  'so we just need something',
  'to give an extra boost of oxygen during that time . ',
  'Like an oxygen generator . ',
  'Exactly . ',
  'So we just need a chemical',
  'thats rich in oxygen that would release it',
  'as a nearly pure gas as it decomposes',
  'something like . ',
  'Sodium chlorate .  Sodium chlorate . ',
  'Then all wed need is heat to release the oxygen . ',
  'Which a speedster generates naturally in the form of lightning . ',
  'I think something like this just might work . ',
  'You think you can help me figure it out ? ',
  'I can certainly try . ',
  'Im not changing my nickname . ',
  'I like Speedy . ',
  'Are you familiar with my body of work ? ',
  'If you are , then you know I can come up with something',
  'so much better than Speedy . ',
  'Why dont you get a haircut ? ',
  'And then maybe we can talk about it . ',
  'I think youre just mad because my conditioner game is on point . ',
  'So the CEO of Palmer Technologies',
  'is living with Oliver Queen . ',
  'Its insane how much life can change in six months ? ',
  'Which you would know better than anyone , ',
  'considering that theres another Flash , ',
  'another Dr . Wells , from another. earth . ',
  'I mean . ',
  'Yeah . No , its been trippy lately . ',
  'I wonder what Olivers doppelganger would look like . ',
  'Bald , potbellied . ',
  'agreeable . ',
  'You seeing anyone ? ',
  'I am , actually .  Good . ',
  'Patty is her name . ',
  'Shes amazing . ',
  'You deserve someone amazing . ',
  'Thanks . ',
  'My pigs in a blanket ! ',
  'Hey , Ollie . ',
  'look , Im sorry that I laid all of this on you . ',
  'I know that it wasnt fair .  Its okay . ',
  'Im sorry if earlier I was a little . ',
  'Snippy ? ',
  'I have been called worse . ',
  'No , but Im glad that youre here . ',
  'Im glad you reached out . ',
  'It shows a real maturity , and I would know that',
  'because Ive never been that mature . ',
  'Im always here for you . ',
  'Thank you . ',
  'I got to say , this isnt the same',
  'Arrow team Im used to seeing',
  'or the same Oliver Queen . ',
  'You seem really.  Happy ? ',
  'Happy , yeah .  I am happy . ',
  'I finally have everything that Ive ever wanted . ',
  'Being with Felicity has given me a real sense of peace , ',
  'something that I havent had in a long time . ',
  'Didnt you tell me that guys like us dont get the girl ? ',
  'Yep . ',
  'I was wrong . ',
  'I would like to propose a toast . ',
  'I wish it wasnt just the dark times bringing us together . ',
  'But it is friends like you',
  'that make those dark times worth having . ',
  'What a guy . ',
  'Steals my drinks , steals my words . ',
  'As I was saying , its good to see everyone . ',
  'Yes .  Cheers . ',
  'Cheers . ',
  'Cheers .  Cheers . ',
  'Look , dont worry , all right ? ',
  'Were gonna keep her safe . ',
  'I promise .  Yeah , I know . ',
  'Look , theres something I never told you . ',
  'The first time I kissed Kendra , I got a vibe . ',
  'No , not like that kind of vibe . ',
  'Like , I vibed vibed . ',
  'Remember the man with wings ? ',
  'It wasnt a man . ',
  'It was Kendra . ',
  'She was , like , a bird . ',
  'You think that shes a metahuman ? ',
  'Wait . Why didnt you say anything about this sooner ? ',
  'Well , I didnt think it was related , ',
  'but I guess now it has to be . ',
  'Look , I dont want her to know about my powers . ',
  'I have this great thing going with her . ',
  'She laughs at my jokes , and she loves movies , and . ',
  'I just Ive never felt like this before , ',
  'and I dont want to sabotage it . ',
  'I get the feeling . ',
  'Look ! ',
  'I will always find you , ChayAra . ',
  'Dont move .  Then how will I kill you all ? ',
  'Yeah , I can do that too . ',
  'Thea , no ! ',
  'What did you do ? ',
  'I ended it . ',
  'This is why we ask questions . ',
  'Wait . Wwhere did he go ? ',
  'Oh , boy . ',
  'Okay . ',
  'Thanks . ',
  'All right , Lance is gonna call if he gets any information on . ',
  'whoever that is . ',
  'I know where we can get some info . ',
  'Kendra , I have powers . ',
  'I get these vibes from people . ',
  'Theyre visions of metahumans , ',
  'and I had one of you . ',
  'So , A , youre saying youre a metahuman , ',
  'and , B , shes a metahuman ? ',
  'I dont know . ',
  'In these visions , you could fly . ',
  'It was like you were a bird of some sort . ',
  'A bird ?  Yeah . ',
  'What else did you see ? ',
  'Thats it just you with wings . ',
  'Oh , I did not see that one coming . ',
  'Oh , I think theres a lot you didnt see coming . ',
  'Great . More surprises . Who the hell is this ? ',
  'Its my dad . ',
  'I think I did it . ',
  'What do you know , Snow ? ',
  'I think you did do it . ',
  'Velocity6 ? ',
  'This is what was so urgent , Harrison ? ',
  'You get me to come here so I can take your speed drug ? ',
  'Thats right . ',
  'You knew about this .  Of course she did . ',
  'She figured it out . ',
  'I thought this was to help Barry . ',
  'It is to help Barry , ',
  'which is why we need to do test runs on subjects',
  'who once had the Speed Force in their system . ',
  'The Speed Force doesnt work like that . ',
  'Its not something you can create in a lab . ',
  'How do you think you became The Flash , Garrick ? ',
  'By me and a lab . ',
  'Science is what did this to you , to Barry , to Zoom , ',
  'and science is what we need to stop Zoom , ',
  'and this is our only option . ',
  'Find another one . ',
  'The Speed Force cant be replicated or enhanced . ',
  'Its a living thing . ',
  'Its a gift that was given to me . ',
  'That drug you have no idea what its gonna do . ',
  'Im not going to let another one of your experiments',
  'mess with me again , Harrison . ',
  'You find someone else to be your guinea pig . ',
  'Jay . ',
  'Caitlin , keep that serum away from Barry . ',
  'Where are you going ? ',
  'To pick up what we need . ',
  'Wait . Jay just said we shouldnt give it to Barry . ',
  'Were gonna do what we need . ',
  'The man youre looking for is Vandal Savage . ',
  'Vandal Savage ? Never heard of him . ',
  'Well , who is he ? ',
  'Some say he was the most trusted adviser to Genghis Khan . ',
  'Others say he guided Julius Caesar through the Gallic Wars . ',
  'But one thing the League knows for sure',
  'he was there for all of it . ',
  'So what are you saying ? ',
  'Hes like a vampire or something ? ',
  'Not a vampire , an Immortal . ',
  'Okay , weve officially stepped into crazy town . ',
  'Immortality ? ',
  'Wait . No , no , no , this makes sense . ',
  'This explains why he looks the same as he did in 1975 . ',
  'This cant be possible . ',
  'Theres nothing you can do to save her now . ',
  'Kendra , do not listen to him . ',
  'II just need some air . ',
  'Were gonna do whatever we have to to keep Kendra safe , ',
  'whether you think we can or not . ',
  'Hey , Joe , its Patty . ',
  'I just interviewed a weapons',
  'expert about the flint knife our attacker used . ',
  'Found out something pretty interesting , ',
  'uh , so call me back . ',
  'Harrison Wells ? ',
  'Kendra ! ',
  'You going to be all right ? ',
  'Its just a lot to take in right now . ',
  'Look , Im sorry I didnt tell you about me before . ',
  'I didnt want things to be different between us . ',
  'Its not that , Cisco . ',
  'If what everyones saying is true',
  'and its beginning to seem like it is',
  'my whole life just changed , ',
  'and I am so not ready for that . ',
  'I hear what youre saying . I do . ',
  'When I first learned about my powers , ',
  'I remember feeling that exact same feeling , ',
  'and sometimes I still feel that way , ',
  'and all I can say is . ',
  'every day gets a little bit more normal . ',
  'I promise you . ',
  'Thank you . ',
  'Youre so welcome . ',
  'Kendra ! ',
  'Help ! ',
  'Guys , did you find anything ? ',
  'Im on it ! ',
  'This is my house . ',
  'Dont worry . Were going to find her . ',
  'You look as beautiful as ever . ',
  'ChayAra , its me , Khufu . ',
  'Do you remember ? ',
  'Look at me . ',
  'You need to wake up . ',
  'What are you talking about ? ',
  'I dont know who you are . ',
  'You will once you emerge . ',
  'Until then , you need to stay by my side',
  'so that I can protect you . ',
  'Protect me ? From what ? ',
  'The man whos hunting you , Vandal Savage . ',
  'I got them ! 57th Street tower . ',
  'Im right near there . ',
  'Always a pleasure watching you work , Smoak . ',
  'That was pitiful . ',
  'I know this is a lot to take in , ',
  'but you sort of just kind of have to trust me on this . I . ',
  'Just one second . Stay right there . ',
  'I got eyes on him . ',
  'Give me the girl . ',
  'Not gonna do that , Robinhood . ',
  'Youre making a big mistake . ',
  'Ill take my chances . ',
  'Barry , change of venue . ',
  'Birdman and Oliver are at 54th and Motor nowhurry ! ',
  'On my way ! ',
  'We need to expose his wings . ',
  'Im open to suggestions . ',
  'Now youre listening to me ? ',
  'Its your city , Oliver . ',
  'All right . ',
  'Thats new . ',
  'Yep , comes in handy . ',
  'We cant use that serum on Barry . ',
  'Thats up to him , isnt it ? ',
  'If Barry wants to stop Zoom , this is what he needs . ',
  'Jay said it could hurt Barry . ',
  'Well , Jays a coward . ',
  'Jays a scientist who knows a lot about speedsters . ',
  'Youre a scientist , Snow . Youve been watching Barry . ',
  'You know hes nowhere near as fast as he needs to be . ',
  'This other mentor , this other Harrison Wells , ',
  'did not want him to reach his full potentialI do . ',
  'You know , youre really starting to sound a lot like him . ',
  'Put your hands in the air . ',
  'Who are you ?  Youre under arrest . ',
  'Doctor McGee was right . ',
  'She did see you .  Christina McGee ? ',
  'At Mercury Labs . ',
  'Youre Harrison Wells . ',
  'Yes , Im Harrison Wells . ',
  'Im not the Harrison',
  'Stop ! You move closer , and Ill shoot . ',
  'Give me that',
  'Oh , my God , what have you done ? ',
  'Harrison ? ',
  'Harrison , stay with me . ',
  'Harrison , Harrison , stay with me . ',
  'Stay with me , Harrison , come on . ',
  'Why did you shoot him ? ',
  'I thought that was a gun . Im sorry . Ill call 911 . ',
  'No , dont ! ',
  'Why ?  Because this',
  'Didnt Joe West explain this to you ? ',
  'No .  Just call Joe . ',
  'Okay . ',
  'Where is she ? ',
  'Whats your name ? ',
  'Youre putting her in danger , ',
  'and Im the only one capable of saving her . ',
  'You have a very interesting perspective',
  'on what the word "saving" means . ',
  'Shes the love of my lifetime , sweetheart . ',
  'I was not gonna hurt her . ',
  'You need to let me go . ',
  'ChayAra . ',
  'My name is Kendra Saunders . ',
  'In this life . ',
  'And I amwas Carter Hall , ',
  'but that is not who we are . ',
  'What does that mean ? ',
  'Youre Priestess ChayAra . Im Prince Khufu . ',
  'And were lovers . ',
  'Soul mates . ',
  'Weve been partners for 4,000 years . ',
  'Were drawn to each other in each life , and after we die , ',
  'we reincarnate to find each other again and again and again . ',
  'And now that Ive found you , ',
  'we should really get out of here . ',
  'Okay , Romeo , why dont you pump the brakes ? ',
  'These people cannot protect you from Savage any longer . ',
  'Do you know who Vandal Savage is ? ',
  'In every lifetime , he hunts us down and kills us . ',
  'Hes done its06 times , ',
  'and Im not planning to make its07 . ',
  'Why does he kill you ? ',
  'His life force is tethered to ours . ',
  'Every time he kills us , he becomes more powerful . ',
  'You do the math . ',
  'Youre 0 fors06 , ',
  'and you still think youre her best bet , hmm ? ',
  'Okay , so what we need to do is just find Savage',
  'and get rid of him . ',
  'Well , you cant get rid of him , my friend . ',
  'Oh , yeah ? Watch us . ',
  'It might be harder than you think . ',
  'Is that the only way this guy knows how to enter a room ? ',
  'My associates tell me',
  'Savage left Star City a few hours ago . ',
  'For where ?  Were not quite sure . ',
  'But I assume after his runin with you , ',
  'he realized he needed something more powerful',
  'to complete his mission . ',
  'We think hes trying to locate the Staff of Horus . ',
  'Sorry , what is that ? ',
  'Its a relic from our past',
  'an ancient and powerful weapon . ',
  'If Savage gets his hands on it , ',
  'its going to be nearly impossible to stop him . ',
  'Since when did our lives',
  'suddenly become an "Indiana Jones" movie ? ',
  'Felicity ?  Yeah ? ',
  'Think you can find it ? ',
  'Yeah . Its probably at some museum somewhere . ',
  'Ill , uh , work my magic , see what I can find . ',
  'Were running out of time . ',
  'You need to emerge now . ',
  'Come on , what is it gonna take for you to believe me ? ',
  'You saw my wings . ',
  'I know you know this is true . ',
  'Please , just let me show you how . ',
  'Hows he doing ?  Hes losing oxygen . ',
  'I need you to leave .  Joe , I',
  'Patty , go . ',
  'Theres a bullet in a branch of his pulmonary artery',
  'thats blocking off most of the blood flow from the left lung . ',
  'Are we able to get the bullet out ? ',
  'Not without causing too much damage . ',
  'I need Jays help . ',
  'So . ',
  'you just want me to jump . ',
  'Fall , jump , swan dive , whatever suits you . ',
  'Just , uh , do it . ',
  'Okay , this isnt the X Games . ',
  'And this is how she emerges',
  'she just falls towards her death ? ',
  'Yep . 4,000 years of experience says thats exactly how . ',
  'Just watch and learn . ',
  'No , Im sorry . What are we doing ? ',
  'Why are we listening to this guy ? ',
  'Come on , Oliver , ',
  'youre supposed to be the one who asks questions . ',
  'Okay , but after what we saw , after what Cisco said , ',
  'I cannot believe Im going to say this , but it . ',
  'kind of makes sense . ',
  'I need to try . ',
  'Are you serious ? ',
  'Yes , she is . ',
  'Barry ! ',
  'What the hell was that ? ',
  'Saving her life . ',
  'You should have emerged . ',
  'Something is blocking you . ',
  'Well , we should just try again and see whats . ',
  'No !  Yeah , no , no , no , no . ',
  'Were not doing that again . ',
  'Kendra , you dont have to do this . ',
  'Oliver , we can stop Savage , okay ? ',
  'Barry . Barry ! ',
  'What ? ',
  'Talk to you for a second ? ',
  'Okay . ',
  'Keep an eye on him . ',
  'What is going on with you ? ',
  'Im trying to keep her alive . ',
  'Then I think we let her jump . ',
  'Are you kidding ? ',
  'Barry , I get that youre desperate to help',
  'and you want to be the hero',
  'and you want to save her yourself , ',
  'but I think she has to have a part in it too . ',
  'What ? ',
  'Its justthe rules keep changing . ',
  'One day I have to run through time , ',
  'the next Im fighting a telepathic gorilla , ',
  'and now were what ? ',
  'Were chasing down an immortal madman on a rampage',
  'against down a reincarnated warrior priestess ? ',
  'I just never thought Id have superpowers',
  'and feel more powerless than I ever have in my entire life . ',
  'That part I understand . ',
  'But you have already helped Kendra . ',
  'You have kept her alive . ',
  'So now lets help her get her wings , ',
  'and then she can give you a lift back to Central City . ',
  'Central City . ',
  'What ?  You need to check Central City for the staff . ',
  'Kendra , you said you were drawn there . ',
  'Yeah .  I think youre drawn to things that destroy you',
  'the same way you two are drawn to each other . ',
  'Thats why it wasnt in any museum or private collection , ',
  'because it was consecrated eight months ago',
  'at St . Marks in Central City . ',
  'Weve got to get it before Savage does . ',
  'Carter , stay here . ',
  'Im not going anywhere . ',
  'Call Thea and Digg , ',
  'and well have them hold down the fort',
  'in case Savage shows up . ',
  'Kendra , last year , I lost my powers . ',
  'The only way I could get them back',
  'is if I just forgot about everything happening around me',
  'and focused on who I was . ',
  'Just believe in yourself , and your true self will emerge . ',
  'Thanks . ',
  'Hey , are you sure that you want to do this ? ',
  'If this guys immortal',
  'and Merlyns right about how powerful this staff is . ',
  'Well be fine . ',
  'Kiss her . ',
  'Well be fine . ',
  'Careful .  Lets go . ',
  'Now what ? ',
  'His systolic pressures dropping . ',
  'Hes gonna code . ',
  'How bad is it ? ',
  'Theres a bullet in his pulmonary artery . ',
  'Can you close the wound if I get it ? ',
  'Yes . ',
  'How are you going to do that ? ',
  'What is that ? ',
  'Its a serum called Velocity6 . ',
  'It could give Jay temporary speed . ',
  'He can phase through Doctor Wells chest',
  'and remove the bullet . ',
  'Yeah , but I told you , ',
  'I have no idea whats gonna happen if I use that . ',
  'Its our only option . ',
  'If you dont do this , Dr . Wells will die . ',
  'Its working . ',
  'BP and oxygenation is rising . ',
  'Blood flows returning to his lungs . ',
  'Thank you . ',
  'I was just thinking . ',
  'all the moments of my life when I felt different , ',
  'like something was wrong with me . ',
  'Now I know why . ',
  'Its gonna be all right . ',
  'Okay ? ',
  'Look , II know what its like to have your life',
  'suddenly change like this . ',
  'II can help you get through this . ',
  'I dont know if you can . ',
  'Cisco , theres a whole other life inside me , ',
  'hundreds of lives , that I need to know about . ',
  'I think I need to do it by myself . ',
  'I have to . ',
  'embrace my destiny . ',
  'I have to believe . ',
  'You dont have to do this . ',
  'Whats going on ? ',
  'Nothing . I just like to speed into rooms , usually . ',
  'Where do you think we find this thing ? ',
  'I havent been in one of these places in a while . ',
  'Were too late . ',
  'Something youre not used to saying very often , ',
  'Id imagine . ',
  'You tried those arrows once before , remember ? ',
  'They didnt quite finish the job , now , did they ? ',
  'Im not gonna make that mistake again . ',
  'Youre gonna leave Kendra alone . ',
  'I cant do that . ',
  'While my destiny is to live forever , ',
  'ChayAras is to die , as is yours now . ',
  'Any ideas ?  Oh , now youll listen to me ? ',
  'Its your city . ',
  'All right , lets just try to get the staff . ',
  'All right , on my mark . ',
  'All right . ',
  'Carter was right . ',
  'Somethings holding me back . ',
  'Maybe its Central City or you',
  'or what I thought my life was gonna be , ',
  'but Im never gonna become who I really am unless I let go . ',
  'I have to do this . ',
  'In all my countless years , ',
  'Ive never encountered anybody with your capabilities . ',
  'Astonishing ! ',
  'No ! ',
  'ChayAra . ',
  'Oh , my God ! ',
  'I used to enjoy slow deaths . ',
  'Now I just find them boring . ',
  'Thanks . ',
  'Any chance he blew himself up in there ? ',
  'Not likely . ',
  'So thats , like , a tie , right ? ',
  'I guess .  I will take it . ',
  'You okay ? ',
  'Im gonna have to learn how to use these things . ',
  'Youll get the hang of it , Hawkgirl . ',
  'Dr . Wells ? ',
  'Youre gonna be okay . ',
  'Thats good news . ',
  'You will probably be very sore for a little while , though . ',
  'Sore is better than dead . ',
  'Yes , it is . ',
  'How are you doing , Garrick ? ',
  'Your serums out of my system , ',
  'and I will never take it again . ',
  'Jay . ',
  'thank you . ',
  'You can thank me by keeping that Velocity6 away from Barry . ',
  'That was Oliver . ',
  'Savage has the Staff of Horus . ',
  'He wants us all in Central City as soon as possible . ',
  'Okay , well , Laurels already there visiting her mom , ',
  'so Ill call her and let her know were coming by . ',
  'If Savage is in Central City , ',
  'then why are we going back there ? ',
  'So we can end this . ',
  'And if anybodys gonna take down Savage , ',
  'its going to be Barry and Oliver . ',
  'Plus , youve emerged . ',
  'Its going to be much harder for him now . ',
  'And together , all of us , ',
  'we can take him down once and for all . ',
  'Okay , so how are we gonna get there ? ',
  'Did I mention Im the CEO',
  'of a big company with a private jet ? ',
  'Since when is that a thing ? ',
  'About eight months . ',
  'Maybe if you save Star City , you might get one too . ',
  'By the way , we still need to get Savage . ',
  'Well get him . ',
  'Watch yourself , buddy . ',
  'You dont want to lose this guy . ',
  'Thanks , mister . ',
  'Yeah . '
]
